### ISSUE TITLE
Make tagged releases

### ISSUE THREAD

**Issue by PureTryOut** [builderjer/tmdb-skill#12]
Hey, thanks for this skill!

I've been packaging Mycroft for Alpine Linux (which I think is the first distribution to do so) and am currently packaging all the different skills available. The idea is to make all skills available as distro packages and not use the current Mycroft marketplace and Pip to install them. I'd love to package your skill as well, but will need a tagged (`git tag`) release to do so.

Please consider making tagged release so that distributions like Alpine Linux and in the future others can package them and keep track of updates.

**Comment by builderjer** [comment]
I don't have a problem doing this.  Do you just need it tagged "release"?

**Comment by PureTryOut** [comment]
No with version numbers please. E.g. make a 1.0.0 release now, and each time you update your skill for the Mycroft marketplace, make a new release (1.0.1, 1.1.0 or 2.0.0).

**Comment by builderjer** [comment]
Released a tag for you.  I am closing the issue now.

**Comment by PureTryOut** [comment]
Thanks, that'll do!
